name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - name: Checkout 코드
      uses: actions/checkout@v3

    - name: Python 설치
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 테스트 실행
      run: |
        python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 코드
      uses: actions/checkout@v3


    - name: Heroku CLI 설치
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Git 초기화 및 Heroku 리모트 추가
      run: |
        git init
        git remote add heroku https://git.heroku.com/farmlog-b.git
        git config user.name "Heroku-Deploy"
        git config user.email "you@example.com"

    - name: Heroku에 배포
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}